
[[sec-overview]]
== General

=== Introduction
This S-411 Data Classification and Encoding Guide (DCEG) contains rules and guidance for converting data describing the real world into data products that conform to the S-411 specification.

The S-411 specification contains an application schema (UML model) describing the conceptual domain model in terms of classes and a Feature Catalogue (see S-411 Annex B) that specifies the data model, i.e., specifies the data model types corresponding to the various classes in the application schema.

To simplify the DCEG text, the various data model types will be provided without the suffixes “class”, “type” or “instance”; e.g. the term “feature” should be understood as “feature class” or “feature type” or “feature instance” as best fits the immediate context in which it is used (and where there might be confusion, it is written out in full as feature class/type/instance).The model defines real world entities as a combination of descriptive and spatial characteristics (S-411 Product Specification clause 6).

This clause of the DCEG contains general information needed to understand the encoding rules and describes fundamental common rules and constraints. It also describes datasets and metadata. The data model object types used within S-411 and their encoding rules and guidelines are defined in detail in subsequent clauses of this document.

Within this document the features and attributes appear in *bold text* or _italic text_, to distinguish them from surrounding words.

=== Descriptive characteristics

==== Feature
A feature contains descriptive attributes that characterize real world entities.

The word ‘feature’ as used in the ISO 191xx series and in S-100 based product specifications has two distinct but related senses – ‘feature type’ and ‘feature instance’. A feature instance is a single occurrence of the feature and is represented as an object in a dataset.

The location of a feature instance on the Earth’s surface is indicated by a relationship to one or more spatial primitive instances.

S-411 only makes use of the *Geographic (Geo) feature type* which carries the descriptive characteristics of a real-world entity.

==== Geographic feature class

*Geographic (Geo) feature types* carry the descriptive characteristics of a real world entity which is
provided by a spatial primitive instance.

==== Meta feature class

*Meta feature type* contains information about other features.

==== Charted background feature

The data product would mostly be visualized as an overlay of an ENC or other GIS applications. Consequently, all necessary descriptive and spatial characteristics to provide a charted background should be provided by the 
underlying application.

=== Spatial characteristics

==== Spatial primitives

The allowable geometric primitive for each feature type is defined in the Feature Catalogue. Allowable geometric primitives are point, curve and surface. Each spatial value must be referenced by at least one feature instance.

Within this document, allowable primitives are included in the description of each feature type. For easy reference, Table 2-1 below summarises the allowable geometric primitives for each feature. In the Table, abbreviations are as follows: point (P), curve (C) and surface (S).


[%unnumbered]
[[tab-features-spatial-primitives]]
.Features and their spatial primitives
[cols="5,1,1,1",options="headers"]
|===
|Feature |P |C |S

4+|[.underline]#*Geographic Features*#

|Floeberg
|P
|
|

|Grounded Hummock
|P
|
|

|Ice Compacting
|P
|
|

|Ice Divergence
|P
|
|

|Ice Drift
|P
|
|

|Ice Edge
|
|C
|

|Ice Fracture
|
|C
|

|Ice Keel/Bummock
|P
|
|

|Ice Lead
|
|C
|

|Ice Rafting
|P
|
|


|Ice Ridge/Hummock
|P
|
|

|Ice Shear
|P
|
|

|Ice Thickness
|P
|
|

|Iceberg
|P
|
|

|Iceberg Area
|
|
|S

|Iceberg Limit
|
|C
|

|Jammed Brash Barrier
|P
|
|

|Lake Ice
|
|
|S

|Limit of All Known Ice
|
|C
|

|Limit of Open Water
|
|C
|

|Line of Ice Crack
|
|C
|

|Line of Ice Fracture
|
|C
|

|Line of Ice Lead
|
|C
|

|Line of Ice Ridge
|
|C
|

|Sea Ice
|
|
|S

|Seperate Giant Floe *(TBC)*
|P
|
|


|Snow Cover
|P
|
|

|Stage of Melt
|P
|
|

|Strips and Patches
|P
|
|

|===

== Geo Features

=== Sea Ice

[width="100%",cols="5,5,5,1,1"]
|===

5+|[.underline]#IHO Definition:# *SEA ICE* is an area at sea that is covered, in whole or in part, with ice.
5+|[.underline]#*S-101 Geo Feature:# Military Practice Area (MIPARE)*
5+|[.underline]#*Primitives:# Point, Surface*

|*S-411 Attribute* |*S-57 Acronym* |*Allowable Encoding Value* |*Type |Multiplicity*

|Total Concentration
|(ICEACT)
|
|EN
|0,0

|Partial Concentration
|(ICEAPC)
|
|EN
|0,0

|===

== Geo Feature Attribute and Enumerate Descriptions
