:sectnums:
[[sec-overview]]
== Overview

=== Scope

This document has been produced by the BSH as part of JCOMM/ETSI in response to a requirement to produce an ice data product that can be used within Electronic Chart Display and Information Systems.

The Ice Information product specification is based on the IHO S-100 framework specification, Geography Markup Language (GML) Encoding Standard and the ISO 19100 series of standards. It is a vector product specification that is primarily intended for encoding the extent and nature of Sea Ice for navigational purpose.

[bibliography]

=== References

GML - OpenGIS® Geography Markup Language (GML) Encoding Standard (Version 3.2.1)

IHO S-100 - IHO Universal Hydrographic Data Model, Edition 5.2.0, June 2024

ISO-19115-1 - ISO 19115-1:2014/Amd 1:2018, Geographic information - Metadata - Part 1: Fundamentals - Amendment 1

ISO-19115-2 - ISO 19115-2:2009/Amd 1:2018, Geographic information - Metadata - Part 2: Extensions for imagery and gridded data

ISO-19115-3 - ISO 19115-3:2016, Geographic information - Metadata - Part 3: XML Schema implementation for fundamental concepts

ISO-19139-1 - ISO 19139-1:2019, Geographic information - XML schema implementation - Part 1: Encoding rules

=== Terms, definitions and abbreviations

==== Use of language

Within this document:

* "`Must`" indicates a mandatory requirement.
* "`Should`" indicates an optional requirement, that is the recommended process to be followed, but is not mandatory.
* "`May`" means "`allowed to`" or "`could possibly`" and is not mandatory.


==== Terms and definitions

_There are no definitions in current version of S-411. Do I delete the ones here after?_

===== Accuracy

No reference to Accuracy in S-411 1.1.0.

===== Coordinate

One of a sequence of _n_ numbers designating the position of a point in N-dimensional space.

NOTE: The numbers must be qualified by units and CRS.

===== Coordinate Reference System

*Coordinate* system which is related to the real world by a datum.

===== Coverage

*Feature* that acts as a function to return values from its range for any direct position within its spatial, temporal, or *spatiotemporal domain*.

NOTE: In other words, a coverage is a feature that has multiple values for each attribute type, where each direct position within the geometric representation of the feature has a single value for each attribute type.

[example]
Examples include a digital image, polygon overlay, or digital elevation matrix

===== Coverage Geometry

Configuration of the *domain* of a *coverage* described in terms of *coordinates*.

===== Direct Position

Position described by a single set of *coordinates* within a *coordinate reference system*.

===== Domain

Well-defined set.

NOTE: Domains are used to define the domain set and range set of attributes, operators, and functions.

===== Depth

The vertical distance from a given water level to the bottom. In this standard, depth refers to the S-32 definition of "Depth Charted".

NOTE: The numbers must be qualified by units and datum. 

===== Feature

Abstraction of real-world phenomena.

NOTE: A feature may occur as a type or an instance. Feature type or feature instance should be used when only one is meant.

===== Feature Attribute

Characteristic of a *feature*.

NOTE: A feature attribute type has a name, a data type, and a domain associated to it. A feature attribute instance has an attribute value taken from the value domain of the feature attribute type.

===== Function

Rule that associates each element from a *domain* (source, or domain of the function) to a unique element in another domain (target, co-domain, or *range*).

NOTE: The range is defined by another domain.

===== Geometric Object

Spatial object representing a set of *direct positions*.

NOTE: A geometric object consists of a geometric primitive, a collection of geometric primitives, or a geometric complex treated as a single entity. A geometric object may be the spatial characteristics of an object such as a feature or a significant part of a feature.

===== Grid

No reference to Grid in S-411 1.1.0.

===== Grid Point

No reference to Grid Point in S-411 1.1.0.

===== Lidar

No reference to Lidar in S-411 1.1.0.

===== Navigation Surface

No reference to Navigation Surface in S-411 1.1.0.

===== Range <coverage>

No reference to Range in S-411 1.1.0.

===== Record

No reference to Record in S-411 1.1.0.

===== Rectified Grid

No reference to Rectified Grid in S-411 1.1.0.

===== Referenceable Grid

No reference to Referenceable Grid in S-411 1.1.0.

===== Sonar

No reference to Sonar in S-411 1.1.0.

===== Spatiotemporal Domain <coverage>

No reference to Spatiotemporal Domain in S-411 1.1.0.

===== Surface

No reference to Surface in S-411 1.1.0.

===== Uncertainty

No reference to Uncertainty in S-411 1.1.0.

===== Vector

Quantity having direction as well as magnitude.

NOTE: A directed line segment represents a vector if the length and direction of the line segment are equal to the magnitude and direction of the vector. The term vector data refers to data that represents the spatial configuration of features as a set of directed line segments.


==== Abbreviations
This Product Specification adopts the following convention for presentation purposes:

CRS Coordinate Reference System

ECDIS Electronic Chart Display and Information System

EPSG European Petroleum Survey Group

ETSI Expert Team on Sea Ice

GML Geography Markup Language

IHO International Hydrographic Organization

ISO International Organization for Standardization

JCOMM Joint Technical Commission for Oceanography and Marine Meteorology

XML eXtensible Markup Language

=== General S-411 data product description

*Title*:: Ice Information Product Specification.

*Abstract*:: To be written by GCOMM

*Acronym*:: S-411

*Content*:: Datasets conforming to this specification will contain all relevant Ice
information for the area of coverage. Additionally there will be relevant
metadata data quality, production authority, data sources and
publication date.The DCEG provides guidance on how data product content must be captured. <<annex-data-classification-and-encoding-guide>>, in addition to [[acstart]]<<tsf>>[[acend]], will provide implementation guidance for developers.

*Spatial Extent*::
*Description*: Global coverage of maritime areas. +
*East Bounding Longitude*: 180° +
*West Bounding Longitude*: -180° +
*North Bounding Latitude*: 90° +
*South Bounding Latitude*: -90°

*Purpose*:: Describing marine protNavigation in ice covered regions

// ported from S-122 product specification.

=== Product Specification metadata
This information uniquely identifies this Product Specification and provides information about its creation and maintenance. For further information on dataset metadata, see <<sec-metadata>>.

*Title*:: Marine Protected Area Product Specification
*S-100 Version*:: 5.2.0
*S-122 Version*:: 1.2.1
*Date*:: xx 2025

*Language*:: English (optional additional)
*Classification*:: Unclassified
*Contact*::
+
--
International Hydrographic Organization +
4 Quai Antoine 1er +
B.P. 445 +
MC 98011 MONACO CEDEX +
Telephone: +377 93 10 81 00 +
Fax: +377 93 10 81 40 +
Email: mailto:info@iho.int[] +
--
*URL*:: link:http://www.iho.int/[www.iho.int]
*Identifier*:: S-411
*Maintenance*:: Changes to the Product Specification S-411 are coordinated by the JCOMM, and must be made available via the IHO web site. Maintenance of the Product Specification must conform to IHO Resolution 2/2007, as amended.

=== IHO Product Specification Maintenance

==== Introduction
Changes to S-411 will be released by the IHO as a New Edition, revision, or clarification.

==== New Edition
_New Editions_ of S-411 introduce significant changes. _New Editions_ enable new concepts, such as the ability to support new functions or applications, or the introduction of new constructs or data types. _New Editions_ are likely to have a significant impact on either existing users or future users of S-122. All cumulative _revisions_ and _clarifications_ must be included with the release of approved New Editions.

==== Revision
_Revisions_ are defined as substantive semantic changes to S-411. Typically, _revisions_ will change S-122 to correct factual errors; introduce necessary changes that have become evident as a result of practical experience or changing circumstances. A _revision_ must not be classified as a clarification. Revisions could have an impact on either existing users or future users of S-411. All cumulative _clarifications_ must be included with the release of approved _revisions_.

Changes in a revision are minor and ensure backward compatibility with the previous versions within the same Edition. Newer revisions, for example, introduce new features and attributes. Within the same Edition, a dataset of one version could always be processed with a later version of the Feature and Portrayal Catalogues.

In most cases a new feature or portrayal catalogue will result in a _revision_ of S-411.

==== Clarification
_Clarifications_ are non-substantive changes to S-122. Typically, _clarifications_: remove ambiguity; correct grammatical and spelling errors; amend or update cross references; insert improved graphics in spelling, punctuation and grammar. A _clarification_ must not cause any substantive semantic change to S-411.

Changes in a _clarification_ are minor and ensure backward compatibility with the previous versions within the same Edition. Within the same Edition, a dataset of one clarification version could always be processed with a later version of the Feature and Portrayal Catalogues, and a Portrayal Catalogue can always rely on earlier versions of the Feature Catalogue.


==== Version Numbers
The associated version control numbering to identify changes (n) to S-411 must be as follows:

New Editions denoted as **n**.0.0

Revisions denoted as n.**n**.0

Clarifications denoted as n.n.**n**
