
[[sec-overview]]
== Overview
=== Introduction
S-411 is the Ice Information Product Specification, produced by the World Meteorological Organization (WMO)/Intergovernmental Oceanographic Commission Technical Commission for Oceanography and Marine Meteorology (JCOMM) Expert Team on Sea Ice (ETSI). +
This document has been produced in response to a requirement to produce a data product that can be used as an Information Overlay within an Electronic Chart Display and Information Systems (ECDIS). It is based on the IHO S-100 framework specification, the ISO 19100 series of standards and Geography Markup Language (GML). It is a vector product specification that is intended for encoding the extent and nature of Sea Ice for navigational purpose in ice covered regions.

=== Scope
This document describes an S-100 compliant Product Specification for Ice Information, which will form an overlay layer for an S-100 based marine navigation system. It specifies the content, structure, and metadata needed for creating a fully compliant S-411 product and for its portrayal within an S-100 system. +
This Product Specification includes the content model, the encoding, the Feature Catalogue, Portrayal Catalogue, and metadata.


[[bibliography]]
=== References
* [[[iho-s100,IHO S-100 5.2.0]]]

* [[[iho-s44,IHO S-44]]]

* [[[iho-s4,IHO S-4]]]

* [[[iho-s32,IHO S-32]]]

* [[[iso-8601,ISO 8601:2004]]]

* [[[iso-639-2,ISO 639-2:1998]]]

**more?**

==== Normative
GML OpenGIS®:: _Geography Markup Language (GML) Encoding Standard_ (Version 3.2.1)
S-97:: _IHO Guidelines for Creating S-100 Product Specifications_, Edition 1.1.0, June 2020.
S-100:: _IHO Universal Hydrographic Data Model_, Edition 5.2.0, June 2024
WMO-No. 574:: _Sea-ice Information and Services_, 2024 edition

==== Informative
ISO 19101:: _Geographic Information – Reference Model_, 2003
ISO 19103:: _Geographic Information – Conceptual Schema Language_, 2005
ISO 19103-2:: _Geographic Information – Conceptual Schema Language – Part 2_, 2005
ISO 19109:: _Geographic Information – Rules for Application Schema_, 2005
ISO 19110:: _Geographic Information – Methodology for Feature Cataloguing_, 2005
ISO 19111:: _Geographic Information – Spatial Referencing by Coordinates_, 2007
ISO 19115-1:: _Geographic information - Metadata - Part 1: Fundamentals_ - 2014/Amd 1: 2018
ISO 19115-3:: _Geographic information - Metadata - Part 3: XML Schema implementation for fundamental concepts_ - 2016
ISO 19117:: _Geographic Information – Portrayal_, 2012
ISO 19131:: _Geographic Information – Data Product Specifications_, 2008
ISO 19139-1:: _Geographic information - XML schema implementation - Part 1: Encoding rules_ - 2019

=== Terms, definitions and abbreviations

==== Use of language

Within this document:

* "`Must`" indicates a mandatory requirement.
* "`Should`" indicates an optional requirement, that is the recommended process to be followed, but is not mandatory.
* "`May`" means "`allowed to`" or "`could possibly`" and is not mandatory.


==== Terms and definitions

#_The definitions hereafter have been copied from other S-1xx PS. The list has to be reviewed by JCOMM-ETSI_#

*Application Schema*

Conceptual schema for data required by one or more applications.

*Attribute*

(1) Named property of an entity.

NOTE:: Describes a geometrical, thematic, or other characteristic of an entity.

(2) Feature within a classifier that describes a range of values that instances of the classifier may hold.

NOTE:: An attribute is semantically equivalent to a composition association; however, the intent and usage is normally different.

NOTE:: “Feature” used in this definition is the UML meaning of the term.

*Boundary*

Set that represents the limit of an entity.

NOTE:: Boundary is most commonly used in the context of geometry, where the set is a collection of points or a collection of objects that represent those points.

*Coordinate*

One of a sequence of _n_ numbers designating the position of a *point* in N-dimensional space.

NOTE:: In a *coordinate reference system*, the coordinate numbers are qualified by units.

*Coordinate Reference System*

*Coordinate* system which is related to an object by a datum.

*Curve*

1-dimensional geometric primitive, representing the continuous image of a line.

NOTE:: The boundary of a curve is the set of points at either end of the curve. If the curve is a cycle, the two ends are identical, and the curve (if topologically closed) is considered to not have a boundary. The first point is called the start point, and the last is the end point. Connectivity of the curve is guaranteed by the "continuous image of a line" clause. A topological theorem states that a continuous image of a connected set is connected.

#*Data Quality*#

#_A set of elements describing aspects of quality, including a measure of quality, an evaluation procedure, a quality result, and a scope._#

#_No quality data in the current PS. TBC_#

*Data Type*

Specification of a value domain with operations allowed on values in this domain.

NOTE:: Data types include primitive predefined types and user-definable types.

NOTE:: A data type is identified by a term, for example Integer.

*Dataset*

An identifiable collection of data.

NOTE:: A dataset may be a smaller grouping of data which, though limited by some constraint such as spatial extent or feature type, is located physically within a larger dataset. Theoretically, a dataset may be as small as a single feature contained within a larger dataset. A hardcopy map or chart may be considered a dataset.

*Datum*

Parameter or set of parameters that define the position of the origin, the scale, and the orientation of a *coordinate* system.

#*Depth*#

#_The vertical distance from a given water level to the bottom. In this standard, depth refers to the S-32 definition of "Depth Charted"._#

#*_This definition may need to be adapted by JCOMM-ETSI_*#

NOTE:: The numbers must be qualified by units and datum._#

*ECDIS*

A navigation information system which with adequate back-up arrangements can be accepted as complying with the up-to-date chart required by regulations V/19 and V/27 of the 1974 SOLAS Convention, as amended, by displaying selected information from a System Electronic Navigational Chart (System Database) with positional information from navigation sensors to assist the Mariner in route planning and route monitoring, and if required display additional navigation-related information.

*Enumeration*

A fixed list of valid identifiers of named literal values. Attributes of an enumerated type may only take values from this list.

*Feature*

Abstraction of real-world phenomena.

NOTE:: A feature may occur as a type or an instance. Feature type or feature instance should be used when only one is meant.

*Feature*

Abstraction of real world phenomena.

NOTE:: A feature may occur as a type or an instance. Feature type or feature instance should be used when only one is meant.

*Feature Attribute*

Characteristic of a *feature*.

NOTE:: A feature attribute type has a name, a data type, and a domain associated to it. A feature attribute instance has an attribute value taken from the value domain of the feature attribute type.

*Feature Catalogue*

A catalogue containing definitions and descriptions of the *feature* types, *feature attributes* occurring in one or more sets of geographic data.

*Geometric Primitive*

Geometric object representing a single, connected, homogeneous element of geometry.

NOTE:: Geometric primitives are non-decomposed objects that present information about geometric configuration. They include points, curves and surfaces.

*Multiplicity*

Specification of the number of possible occurrences of a property, or the number of allowable elements that may participate in a given relationship.

EXAMPLES: 1..* (one to many); 1 (exactly one); 0..1 (zero or one)

*Point*

0-dimensional geometric primitive, representing a position.

NOTE:: The boundary of a point is the empty set.

*Portrayal Catalogue*

Collection of defined portrayals for a feature catalogue.

NOTE:: Content of a portrayal catalogue includes portrayal functions, symbols, and portrayal context.

==== Abbreviations
This Product Specification adopts the following convention for presentation purposes:

BSH:: Bundesamt für Seeschifffahrt und Hydrographie (Germany)
CRS::  Coordinate Reference System
ECDIS:: Electronic Chart Display and Information System
ENC:: Electronic Navigational Chart
EPSG:: European Petroleum Survey Group
ETSI:: Expert Team on Sea Ice
GML:: Geography Markup Language
IHO:: International Hydrographic Organization
ISO:: International Organization for Standardization
JCOMM:: Joint Technical Commission for Oceanography and Marine Meteorology
UTF-8:: Unicode Transformation Format-8
WMO:: World Meteorological Organization
XML:: eXtensible Markup Language

=== General data product description

*Title*:: Ice Information Product Specification.

*Abstract*:: Ice Information for ship navigation

*Acronym*:: S-411

*Content*:: Ice features as vector data

*Spatial Extent*::

*Description*: Areas specific to navigation in ice covered regions. +
*East Bounding Longitude*: 180° +
*West Bounding Longitude*: -180° +
*North Bounding Latitude*: 90° +
*South Bounding Latitude*: -90°

*Purpose*:: Navigation in ice covered regions

// ported from S-122 product specification.

=== Product Specification metadata

*Title*:: Ice Information Product Specification
*S-100 Version*:: 5.2.0
*S-411 Version*:: 1.1.0
*Date*:: 15 June 2014
*Language*:: English (optional additional)
*Classification*:: Unclassified
*Contact*:: Jürgen Holfort (ice@bsh.de)
*Identifier*:: JCOMM S-411
*Maintenance*:: Changes to this product specification are coordinated by ETSI.
+
--
International Hydrographic Organization +
4 Quai Antoine 1er +
B.P. 445 +
MC 98011 MONACO CEDEX +
Telephone: +377 93 10 81 00 +
Fax: +377 93 10 81 40 +
Email: mailto:info@iho.int[] +
--
*URL*:: link:http://www.iho.int/[www.iho.int]
*Identifier*:: S-411
*Maintenance*:: Changes to the Product Specification S-411 are coordinated by the JCOMM, and must be made available via the IHO web site.

=== IHO Product Specification Maintenance

==== Introduction
Changes to S-411 will be released by the IHO as a New Edition, revision, or clarification.

==== New Edition
_New Editions_ of S-411 introduce significant changes. _New Editions_ enable new concepts, such as the ability to support new functions or applications, or the introduction of new constructs or data types. _New Editions_ are likely to have a significant impact on either existing users or future users of S-122. All cumulative _revisions_ and _clarifications_ must be included with the release of approved New Editions.

==== Revision
_Revisions_ are defined as substantive semantic changes to S-411. Typically, _revisions_ will change S-411 to correct factual errors; introduce necessary changes that have become evident as a result of practical experience or changing circumstances. A _revision_ must not be classified as a clarification. Revisions could have an impact on either existing users or future users of S-411. All cumulative _clarifications_ must be included with the release of approved _revisions_.

Changes in a revision are minor and ensure backward compatibility with the previous versions within the same Edition. Newer revisions, for example, introduce new features and attributes. Within the same Edition, a dataset of one version could always be processed with a later version of the Feature and Portrayal Catalogues.

In most cases a new feature or portrayal catalogue will result in a _revision_ of S-411.

==== Clarification
_Clarifications_ are non-substantive changes to S-122. Typically, _clarifications_: remove ambiguity; correct grammatical and spelling errors; amend or update cross references; insert improved graphics in spelling, punctuation and grammar. A _clarification_ must not cause any substantive semantic change to S-411.

Changes in a _clarification_ are minor and ensure backward compatibility with the previous versions within the same Edition. Within the same Edition, a dataset of one clarification version could always be processed with a later version of the Feature and Portrayal Catalogues, and a Portrayal Catalogue can always rely on earlier versions of the Feature Catalogue.


==== Version Numbers
The associated version control numbering to identify changes (n) to S-411 must be as follows:

New Editions denoted as **n**.0.0

Revisions denoted as n.**n**.0

Clarifications denoted as n.n.**n**
