
[[sec-data-content-and-structure]]
== Data Content and Structure

=== Introduction
The application schema of ice information product contains 28 feature types with their attributes, enumerations etc. It is based on the ice objects catalogue (Version 5.1) and can also be found in the ICE domain of the IHO Registry. Because of this it is not possible to describe full schema in suitable form in this specification. The full schema can be found as XML Schema File in Annex B – Data Product format (encoding).

=== Application Schema
Picture below shows very simplified structure of ice data structure

#_Figure 1 (UML diagram) to be inserted here_#

General GML (XML) representation:

#_XML code to be inserted here_#

=== Feature Catalogue

==== Introduction
The feature Catalogue for Ice Information contains only geographic features. The ice features which can be used in ECDIS are fully presented in the ICE domain of the IHO Registry.

==== Application Schema implementation classes

===== Implementation classes description

#_4.3.2.1 UML diagram to be inserted here_#

#_I would suggest moving the table to the DCEG (and adpat to the DCEG format)_#

==== Feature types

_IceDataSetType_ is a type of root Element of an ice information data set.

Ice Data Set contains an unlimited number of Ice Feature Members, each Ice Feature Member
contains one Ice Feature (seaice, lacice, iceberg, etc.).

===== Geographic

===== Meta

==== Feature relationship

==== Attributes

===== Simple attributes

===== Complex attributes

=== Dataset types

==== Introduction

At the moment is only one type of dataset supported. This is GML(XML) encoded ice feature
collections

=== Geometry
Ice Information datasets use S-100 Level 3a geometry which supports 0-, 1-, and 2-dimensional
objects (points, line strings, and polygons).

#_Figure 3  to be inserted here._#

There are three types of geometry: Point, Line String and Polygon. Multi-geometries will be not supported. The standard geometries of GML where redefined for S-411. The reason for this is to reduce file sizes. It is only possible to use “posList” with blanks separated coordinate values, like:

[source]
----
<gml:posList>-73.991 40.736 -73.991 40.736</gml:posList>
----

For standard GML it would be also possible to use following (DO NOT USE THIS):
[source]
----
#_gml code to be inserted here._#
----
Which means much more chars in the file and growing of file size.

All multi-geometries must be splitted into single geometries. Encoding for geometry is GML:

Point encoding example:

[source]
----

#_gml code to be inserted here._#

----
Line String encoding example:
[source]
----

#_gml code to be inserted here._#

----
Polygon encoding example:
[source]
----

#_gml code to be inserted here._#

----
