
[[sec-data-quality]]
== Data Quality
Data quality allows users and user systems to assess fitness for use of the provided data. Data quality measures and the associated evaluation are reported as metadata of a data product. This metadata improves interoperability with other data products and provides usage by user groups that the data product was not originally intended for. The secondary users can make assessments of the data product usefulness in their application based on the reported data quality measures.

=== Completeness

==== Commission
Commission is applicable for S-102. Data Producers must verify that no excess items have been included in the dataset. Such excess items include duplicate items, which must be removed.

If no excess items are present, the dataset PASSES this test.

==== Omission
Omission is applicable for S-102. Data Producers must verify that no items that should have been included in the dataset have been omitted.

If no necessary items have been omitted, the dataset PASSES this test.

=== Logical consistency

==== Conceptual consistency
Conceptual Consistency is applicable for S-411 and follows the guidelines from <<iho-s100,part=1>>.

Data Producers must verify that the dataset conforms to the S-100 General Feature Model.

If the dataset conforms to the S-100 General Feature Model, the dataset PASSES this test.

==== Domain consistency
Domain consistency is applicable for S-411 and follows the guidelines from <<iho-s100,part=5>>.

Data Producers must verify that the dataset conforms to the S-102 Feature Catalogue and to <<annex-data-classification-and-encoding-guide>>.

If the dataset conforms to the S-411 Feature Catalogue and to <<annex-data-classification-and-encoding-guide>>, the dataset PASSES this test.

==== Format consistency
Format Consistency is applicable for S-411 and follows the guidelines from <<iho-s100,part=10c>>.

Data Producers must verify that the dataset conforms to <<sec-data-product-format-encoding>> of this Product Specification.

If the dataset conforms to <<sec-data-product-format-encoding>>, the dataset PASSES this test.



=== Positional accuracy

==== Gridded data positional accuracy


==== Relative internal positional accuracy

=== Temporal accuracy

=== Thematic accuracy

==== Thematic classification correctness


==== Non-quantitative attribute accuracy


==== Quantitative attribute accuracy
As defined in <<iho-s100,part=4c>> the data quality for the depth coverage is also defined as a co-located optional coverage, which is the uncertainty. This value particularly refers to the vertical uncertainty at each grid point. The uncertainty coverage supports multiple definitions of vertical uncertainty.

See <<tab-codes-defining-how-bathy-depth-uncertainty-determined>>.

