
[[sec-data-product-delivery]]
== Data Product Delivery

=== Introduction
This clause describes how S-411 data will be delivered from the charting authority to the mariner.

*Units of Delivery*:: Exchange Set

*Transfer Size*:: See <<subsec-dataset-size>>.

*Medium Name*:: Digital Data Delivery

*Other Delivery Information*::
+
--
Each dataset must be contained in a physically separate, uniquely identified file on the transfer medium.

Each exchange set has a single exchange catalogue which contains the discovery metadata for each dataset.

An exchange set is encapsulated into a form suitable for transmission by a mapping called an encoding. An encoding translates each of the elements of the exchange set into a logical form suitable for writing to media and for transmission online. An encoding may also define other elements in addition to the exchange set contents (This is media identification, data extents etc. ...) and may define commercial constructs such as encryption and compression methods.

If the data is transformed in S-411 it must not be changed.

This Product Specification defines the encoding which must be used as a default for transmission of data between parties.

The encoding encapsulates exchange set elements as follows:

*Mandatory Elements*

* S-411 datasets -- HDF encoding
* Exchange Catalogue -- the XML encoded representation of exchange set catalogue features [discovery metadata].

*Optional Elements*

* S-411 Feature Catalogue -- If it is necessary to deliver the latest Feature Catalogue to the end user it may be done using the S-411 exchange set mechanism for datasets
* S-411 Portrayal Catalogue -- If it is necessary to deliver the latest Portrayal Catalogue to the end user it may be done using the S-411 exchange set mechanism for datasets.
--

=== Dataset

==== Dataset management

[[subsec-dataset-size]]
==== Dataset size

[[subsec-dataset-file-naming]]
==== Dataset file naming
Dataset naming must follow a standard pattern to give implementers greater predictability of incoming datasets (see <<iho-s100,part=17,clause=4.3>>). S-411 dataset naming conventions must follow these rules.

*411YYYYØØØØØØØØØØØØ.GML*::
411::: the first 3 characters identify the dataset as an S-411 dataset (mandatory).
YYYY::: the fourth to seventh characters identify the producer code according to the Producer Code Register.
ØØØØ::: the eighth to the maximum nineteenth characters are optional and may be used in any way by the producer to provide the unique file name. The following characters are allowed in the dataset name: A to Z, 0 to 9 and the special character _ (underscore).
GML::: denotes an HDF5 file.

=== Exchange Set
The structure of an S-411 Exchange Set must be according to the structure described below, which is based on <<iho-s100,part=17,clause=4.2>>.

. An S-411 Exchange Set must contain an Exchange Set Catalogue, CATALOG.XML, its digital signature CATALOG.SIGN, and may contain any number of S-411 conformant dataset files, support files, and Catalogue files.

. All content must be placed inside a top root folder named S100_ROOT. This is the only top level root folder in an Exchange Set containing only S-100 products.

. The S100_ROOT folder must contain a subfolder named S-411. This subfolder holds content specific to the S-411 Product Specification.

. The S-411 subfolder must contain subfolders for the component dataset files (DATASET_FILES) and Catalogues (CATALOGUES) as required.

. The required Exchange Set Catalogue XML document instance must be named CATALOG.XML and placed in the S100_ROOT folder, together with its digital signature (CATALOG.SIGN) file. All other digital signatures are included within their corresponding resource metadata records in the CATALOG.XML.

=== Exchange Catalogue
The Exchange Catalogue acts as the table of contents for the Exchange Set. The Catalogue file of the Exchange Set must be named CATALOG.XML. No other file in the Exchange Set may be named CATALOG.XML. The contents of the Exchange Catalogue are described in <<sec-metadata>>.

=== Data integrity and encryption
<<iho-s100,part=15>> defines the algorithms for compressing, encrypting and digitally signing datasets based on the S-100 Data Model. The individual Product Specifications provide details about which of the elements are being used and on which files in the dataset.

==== Use of compression
The data producer decides if compression will be used on the S-411 product files (HDF5). It is expected that a hydrographic office will make a policy decision and that all the S-411 datasets from the producer will be either compressed or uncompressed.

It is recommended to compress all the dataset files, for example HDF5 files. The ZIP compression method defined in <<iho-s100,part=15,clause=5.2>> must be applied to the product files.

==== Use of data protection
It is recommended to encrypt all the dataset files, for example HDF5. The encryption method defined in <<iho-s100,part=15>> must be applied.

==== Use of digital signatures
Digital signatures shall be used on all files included in a S-411 compliant Exchange Set to meet the requirements of IMO resolution MSC.428(98) to reduce cyber security risks among users, especially when used in navigations systems at sea. The recommended signature method is defined in <<iho-s100,part=15>>.

The digital signature information is encoded in the corresponding discovery block in the exchange catalogue for each file included in the Exchange Set.
